import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";  // Correct font imports
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Ensure no whitespace between tags in the <head> */}
      </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`} // Apply fonts
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
